Add SHR and IOL documentation
PharmAccess/hdc-documentation pull request #1
Opened 2024-05-28 06:28 UTC by brianraila

@Ihure 
Kindly help review this

2024-05-28 13:44 UTC, Ihure requested changes
in addition to the comments use `docs/iol/index` to give an overview of what the IOL is and role it plays. I'd like to see the fhir passthrough mentioned and mediator.
show sample of how non-fhir data is converted to fhir via mediator or vice versa. let's start with that more comments will come after second revision

2024-05-28 13:44 UTC, Ihure commented on docs/getting_started.qmd
> +1. Docker - Instructions on how to install Docker can be found on the Docker website
add link to website

2024-05-28 13:44 UTC, Ihure commented on docs/getting_started.qmd
> +`git clone https://github.com/IntelliSOFT-Consulting/MamaToto-HIE.git`
should refer to pharmaccess instance probably a fork of this or repo is transferred

2024-05-28 13:44 UTC, Ihure commented on docs/getting_started.qmd
> +5. Nginx Proxy (Nginx)
will fhir-web be part of this

2024-05-28 13:44 UTC, Ihure commented on docs/iol/challenges/keycloak_intergration.qmd
> +The OpenHIM offers a few authentication mechanisms to verify client interactions with the OpenHIM Core. These mechanisms are JWT Tokens, Custom Tokens, Mutual TLS and Basic Auth. These Authentication
add mechanism as bullets for easy reading

2024-05-28 13:44 UTC, Ihure commented on docs/iol/challenges/keycloak_intergration.qmd
> +The OpenHIM offers a few authentication mechanisms to verify client interactions with the OpenHIM Core. These mechanisms are JWT Tokens, Custom Tokens, Mutual TLS and Basic Auth. These Authentication
add link to overview page

2024-05-28 13:44 UTC, Ihure commented on docs/iol/challenges/keycloak_intergration.qmd
> +
solution is not properly documented, specify the exact configs that had an issue and solution that was found. if different realms are needed etc 
insert code snippets if need be. this needs to be a solution a dev can simply look at and use to fix, stackoverflow style

2024-05-28 13:44 UTC, Ihure commented on docs/iol/challenges/keycloak_intergration.qmd
> +However, this is not a very straight-forward process as there lacks any documentation online on how to set this up or how to troubleshoot.
the challenge does not come out clearly. I.e. what in the configurations need to be set correctly in order for keycloak to work and is the challenge that each component like openhim and proxy need separate configurations or

2024-05-28 13:44 UTC, Ihure commented on docs/iol/challenges/fhir_web.qmd
> +1. Lack of documentation.
be specific in the description of the challenge, i.e specify that fhirweb needed custom config on fhirserver for it to work.

2024-05-28 13:44 UTC, Ihure commented on docs/iol/challenges/fhir_web.qmd
> +   The project is not very well documented therefore
sentence not complete

2024-05-28 13:44 UTC, Ihure commented on docs/iol/instant-v2/instant_v2.qmd
> +
it would be nice to describe a short summary of what each component does and include fhirweb too

2024-05-28 13:44 UTC, Ihure commented on docs/iol/instant-v2/instant_v2.qmd
> +```
if including sample file describe what it's used for and how to implement

2024-05-28 13:44 UTC, Ihure commented on docs/shr.qmd
> +#### MDM Rules.
not complete

2024-05-29 01:00 UTC, brianraila commented
> in addition to the comments use `docs/iol/index` to give an overview of what the IOL is and role it plays. I'd like to see the fhir passthrough mentioned and mediator. show sample of how non-fhir data is converted to fhir via mediator or vice versa. let's start with that more comments will come after second revision

Thanks Chris. This is well noted.

2024-07-17 07:40 UTC, Ihure commented
@brianraila approving this to merge, kindly move this to [instant hie](https://github.com/IntelliSOFT-Consulting/MamaToto-HIE) docs directory and add me as reviewer there

2024-07-17 07:40 UTC, closed without merging